### PR TITLE
Pushover notifcations

### PR DESCRIPTION
**Pull request by Stevaz913**
Added Pushover notification functionality option to trader.js

### CODE REVIEW

**Comment by rolltidehero** [comment]
Thanks, I'll give this a try when I get mine setup. :)

**Comment by le-dawg** [comment]
Lolz, someone did the work before. I should have checked 🤣 I will leave mine up for posterity anyway.

**Comment by Yelles** [comment]
hi @jsappme i really like your project, and this pull request too :)
any reason to not merge this ?

**Review by dargmuesli — CHANGES_REQUESTED** [review]
Good contribution @Stevaz913, but could you move the duplicate code to a separate function? While you're at it, that could be done for email / telegram too :)

**Comment by Yelles** [comment]
I feel that all this has to be refactored to fit the new notification system. 😅

**Comment by dargmuesli** [comment]
Yep, we now have a notification module into which this feature would need to be integrated.

**Comment by dargmuesli** [comment]
The trader script is now going to use Typescript (#111), which is unsupported by the pushover notification library used here. Either a different library has to be used or JavaScript support has to be enabled. Other than that a rewrite would be very quick and easy, now that all code is refactored.
Closing this for now, but any new up-2-date approach is welcome!

**Pull request closed without merging**
