### PR TITLE
Removed not used if statements(btcusdt)

### PR DESCRIPTION
**Pull request by mmarczuk**
All if statements `if (signal.pair == "BTCUSDT")` have been removed, they are not used, so this can help to keep the code clean

### CODE REVIEW

**Comment by dargmuesli** [comment]
@jsappme what was the initial reason for these checks to be implemented?
@mmarczuk what makes you sure they aren't used?

**Comment by jsappme** [comment]
I used to forward test some BTCUSDT strategies with real funds like this
one https://bitcoinvsaltcoins.com/strategy/421

**Comment by dargmuesli** [comment]
So do you think this is still needed or is it ok for you to have it removed?

**Comment by mmarczuk** [comment]
I think if it’s no longer needed, we can keep the code more generic.

**Comment by dargmuesli** [comment]
Yeah, I know since you created the PR, but I'm wondering if @jsappme still sees a reason to keep this ;D

**Comment by jsappme** [comment]
It can be removed

**Pull request merged**
