### PR TITLE
configuration to run the new trader over Heroku

### PR DESCRIPTION
**Pull request by davidlondono**

### CODE REVIEW

**Comment by dederaditya** [comment]
I tried the forked version, but in the end the bot crashed

**Comment by dargmuesli** [comment]
Is this ready for review @davidlondono?
@dederaditya please give a quick feedback when you know more about the issue you mentioned or if this is not applicable anymore.

**Comment by davidlondono** [comment]
with the last update, is working on my Heroku

**Comment by davidlondono** [comment]
Also, when the telegram bot is ready it could be nice to have the Flags also at the `app.json`
@dargmuesli do you think is needed another ENV variable to be exposed?

**Comment by dederaditya** [comment]
Ok, I deployed the new version, and it is working.
I think the issue, there was 2  dynos (server and autotrader) and because of that the bot crashes.
image

**Comment by dargmuesli** [comment]
@davidlondono yep, the other PR is merged now so you can adapt the env vars to this PR now :)
I'll merge this one then.

**Review by dargmuesli — APPROVED** [review]

**Pull request merged**
